import os

cwd = os.path.dirname(__file__)


torax_pa = (f"{cwd}/torax_pa.png")
torax_lat = (f"{cwd}/torax_lat.png")
ester = (f"{cwd}/esternon.png")
p_costal = (f"{cwd}/torax_pa_2.png")
craneo_ap = (f"{cwd}/craneo_ap.png")
craneo_lat = (f"{cwd}/craneo_lat.png")
craneo_senos = (f"{cwd}/tsenos.png")
craneo_atm = (f"{cwd}/cara_blandas.png")
humero_ap = (f"{cwd}/humero_placas.png")
humero_lat = (f"{cwd}/humero_fracturado.png")
cub_rad_ap = (f"{cwd}/muñeca_fractura.png")
codo_ap = (f"{cwd}/codo_90.png")
codo_lat = (f"{cwd}/humero_fracturado.png")
femur_ap = (f"{cwd}/femur_ap_frac.png")
femur_lat = (f"{cwd}/femur_ap_frac.png")
rodilla_ap = (f"{cwd}/rodilla_ap.png")
rodilla_lat = (f"{cwd}/rodilla_lat.png")
abd_bipe = (f"{cwd}/cadera_ap.png")
abd_simple = (f"{cwd}/cadera_ap.png")
abd_lat = (f"{cwd}/cadera_ap.png")
cadera_ap = (f"{cwd}/cadera_ap.png")
cadera_lat = (f"{cwd}/cadera_ap.png")
cadera_rot = (f"{cwd}/cadera_ap.png")
col_c_ap = (f"{cwd}/cervicales_ap.png")
col_c_la = (f"{cwd}/cervicales_lat.png")
col_d_ap = (f"{cwd}/c_lumbar_ap.png")
col_d_la = (f"{cwd}/c_lumbar_lat.png")
col_l_ap = (f"{cwd}/c_lumbar_ap.png")
col_l_la = (f"{cwd}/c_lumbar_lat.png")
col_s_ap = (f"{cwd}/c_lumbar_ap.png")
col_s_la = (f"{cwd}/c_lumbar_lat.png")
